### ISSUE TITLE
ImportError: No module named 'taiga_contrib-gogs'

### ISSUE THREAD

**Issue by emansije** [taigaio/taiga-contrib-gogs#10]
When I try to execute the `python manage.py migrate` command, I get: `ImportError: No module named 'taiga_contrib-gogs'`:

``` bash
(taiga)taiga@taiga:~/taiga-back$ python manage.py migrate taiga_contrib_gogs
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 325, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'taiga_contrib-gogs'
```

I'm using taiga-contrib-gogs version 0.0.9.

There is an obvious issue with the name of the module since it was supposed to be `taiga_contrib_gogs` and not `taiga_contrib-gogs`, as stated in the error message, but I can't find the problem. I tried doing the following commands:

``` bash
(taiga)taiga@taiga:~$ cd /home/taiga/.virtualenvs/taiga/lib/python3.4/
(taiga)taiga@taiga:~/.virtualenvs/taiga/lib/python3.4$ grep "taiga_contrib-gogs" * -R
```

Nothing came up. I assume the module name is built dynamically, but I don't know enough about the process to fix it.

**Comment by bameda** [comment]
Hi @emansije 

try to find `taiga_contrib-gogs` in `taiga-back/settings/local.py`

**Comment by emansije** [comment]
Spot on! I feel so silly for not figuring out my mistake. Thank you so much!

**Comment by bameda** [comment]
Great :smile: 

Don't worry, it's a common mistake for people just getting started with Django.

Feel free to send us your bugs and feedback.
