### ISSUE TITLE
Error while running "migrate taiga_contrib_gogs"

### ISSUE THREAD

**Issue by Jsewill** [taigaio/taiga-contrib-gogs#6]
```
Trying import local.py settings...
Monkey patching...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 63, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 17, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 48, in __init__
    self.build_graph()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/loader.py", line 245, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/graph.py", line 46, in add_dependency
    "Migration %s dependencies reference nonexistent parent node %r" % (migration, parent)
KeyError: "Migration taiga_contrib_gogs.0001_initial dependencies reference nonexistent parent node ('users', '0010_auto_20150414_0936')"
```

**Comment by superalex** [comment]
Hello @Jsewill,

What version of the plugin are you installing?, 0.0.4?, 0.0.3?

**Comment by Jsewill** [comment]
Whatever version running, "pip install taiga-contrib-gogs", gets me.  I'd imagine it installs the stable one...which currently appears to be 0.0.3.

**Comment by superalex** [comment]
It installs the version 0.0.4 version but the version that currently works with the stable release of Taiga is the 0.0.3

Could you try installing it using the following please?

```
pip install taiga-contrib-gogs==0.0.3
```

**Comment by tonydspaniard** [comment]
Hi, I do also have an issue but this time is with the default_language?

```shell
Trying import local.py settings...
Operations to perform:
  Apply all migrations: taiga_contrib_gogs
Running migrations:
  Applying taiga_contrib_gogs.0001_initial...Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "default_language" of relation "users_user" does not exist
LINE 1: ...ll_name", "color", "bio", "photo", "date_joined", "default_l...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 117, in database_forwards
    self.code(from_state.render(), schema_editor)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/taiga_contrib_gogs/migrations/0001_initial.py", line 25, in create_gogs_system_user
    bio="",
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 372, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 921, in execute_sql
    cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "default_language" of relation "users_user" does not exist
LINE 1: ...ll_name", "color", "bio", "photo", "date_joined", "default_l...
                                                             ^
